name: Plot Github Action
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Train ML model
        run: |
          python Main.py  
      - name: Save Plots as Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: plots # The name of the artifact
        path: path/to/plots
